### ISSUE TITLE
Small Typo

### ISSUE THREAD

**Issue by cschwem2er** [wdm0006/twitter-pandas#11]
Hi,

thanks a lot for taking the effort to create this package :)

I just wanted to notice you about a small typo in the installation instructions:

```
pip install git+https://github.com/wdm0006/twitterpandas.git

git clone https://github.com/wdm0006/twitterpandas.git
python setup.py install
```

This should be

```
pip install git+https://github.com/wdm0006/twitter-pandas.git

git clone https://github.com/wdm0006/twitter-pandas.git
python setup.py install
```

Cheers,
Carsten

**Comment by wdm0006** [comment]
Thanks for the catch Carsten, hope you've found the library useful, let me know if you run into any trouble, have any suggestions or would like to contribute.
