### ISSUE TITLE
Add parameter to toggle verbosity of response DF

### ISSUE THREAD

**Issue by wdm0006** [wdm0006/twitter-pandas#23]
cc: @FreddieV4 @averagegohard 

I'm thinking that it may be useful to optionally return a reduced dataframe from many of these methods.  A bunch of them have huge numbers of columns, many of which are probably ignored in most basic analyses, so my thought is to add a boolean parameter to all of them (something like verbose, rich, basic, or similar), that would allow the user to toggle between getting back the full dataframe or one with a reduced number of columns.

What do ya'll (or anyone else) think?  We can discuss the merits or drawbacks of this here, and if we all think it's a good idea can split up the actual effort into more granular issues to work on.

**Comment by freddiev4** [comment]
Right. When I was working on some of the methods, I kept thinking _"Well, is some of this data even needed?"_, and some people might focus only on certain types of data. I thinking having an option to filter out data before they're dropped into a DataFrame/CSV would surely be beneficial.

**Comment by wdm0006** [comment]
@FreddieV4 ok, so let's pick a term to use for that keyword, I suggest "rich", and have it default to False (so by default, users will get back the simpler dataset).  

Then we can make a bunch of issues with the same groupings as before and pick them off to implement it.  I imagine it will be a bit of a discussion along the way to determine what "enough" data actually means for a given method.
