### ISSUE TITLE
Implement direct message methods from tweepy

### ISSUE THREAD

**Issue by wdm0006** [wdm0006/twitter-pandas#3]
Implement twitterpandas methods for each of the dataset returning methods in tweepy's direct message methods grouping.

Examples of how to go about this can be found in the existing client.py, where the user methods group has been implemented. Use cursors wherever possible.

**Comment by FreddieV4** [comment]
Going to give this one a shot

**Comment by freddiev4** [comment]
`direct_messages()`, `get_direct_message()`, and `sent_direct_messages()` would be the methods for this implementation, right?

**Comment by wdm0006** [comment]
Yep!

**Comment by freddiev4** [comment]
Working with `direct_messages()` currently. The data gets pretty messy when calling `data.__dict__`

If you use:

```
def direct_messages(self, since_id=None, max_id=None, count=1, page=0, full_text=False):
        """
        Returns direct messages sent to the user tied to the API keys, in the form
        of a Pandas DataFrame

        :param since_id:
        :param max_id:
        :param count:
        :param page:
        :param full_text:
        :return:
        """

        # get direct messages sent to the user from the API
        data = self.client.direct_messages()
        qrs = data[0].__dict__ 
        print(qrs) # print out one object as an example
        return qrs
```

And in your IDE you run `df = tp.direct_messages()`, you'll be able to see what I'm talking about.

How do you want to parse it?

**Comment by wdm0006** [comment]
Freddie, I'm traveling this weekend so will have to get back to you Tuesday, sorry for the delay.

**Comment by wdm0006** [comment]
So a couple of things:
1. For methods that implement pagination (i.e. take count and page), we can use the cursor/limit syntax that you see in other methods I've already implemented such as followers().  That helps keep the handling of rate limits under-the-hood, and keeps the API consistent across all methods (using limit instead of count). 
2. For data access, it's probably best to not use `__dict__` most of the time.  Either explicitly pull certain variables out of the objects: `blob = {'a': foo.a, 'b': foo.b}`, or use the `foo._json` attribute if it's available to access the raw data from the source. The followers() method is a good example for this as well.

If that doesn't make sense let me know, I'll look deeper into these methods this evening.

**Comment by freddiev4** [comment]
I understand (1), however, it looks like these methods (related to direct messages) don't support pagination, and only lists of objects are returned, and not broken into pages. 

For (2), I can't access raw data from the source using `_json` as that attribute isn't available. Using `__dict__` in this case seems to be a good option. There is a key within the dictionary called `_json`, so you could call `data[0].__dict__['json']`, but that doesn't seem good either.

**Comment by wdm0006** [comment]
for (2) in absence of `_json`, we have to build the dataframe manually.  An example of this would be `rate_limit_status()`. 

It looks like a decent data structure for that would be:
- created_at
- entities.symbols
- entities.hashtags
- entities.urls
- entities.user_mentions
- id
- id_str
- recipient.foo
- recipient.bar
- ...
- recipient_id
- recipient_screen_name
- sender.foo
- sender.bar
- ...
- sender_id
- sender_screen_name
- text

Where sender and recipient each have a respective `_json` attribute that can be flattened to produce fields.  Because these are each big, it may be useful to have a user-settable option to include_user_data or something like that, which would toggle the sender.foo and recipient.foo fields.

**Comment by freddiev4** [comment]
OK. Awesome. I'll be able to do that. 

Just a few questions on further data cleaning (if that's the right term?)

When parsing data, in `entities.urls`, for example, I get back `[{'indices': [1, 24], 'url': 'some_url', 'display_url': 'some_display_url', 'expanded_url': 'some_expanded_url'}]`. Should I just pull out one of those values? Such as `url` or `display_url`?

**Comment by wdm0006** [comment]
I would use both and let the end user drop the column on their end if they want to.

**Comment by freddiev4** [comment]
So there's data I'm unable to see; `entities.user_mentions`, `entities.hashtags`, and `entities.symbols`, so I'm not entirely sure how to parse them, if someone were to have this data binded to their API keys.

I did find the link to the [Official Twitter API](https://dev.twitter.com/overview/api/entities-in-twitter-objects#user_mentions), which describes the JSON objects

**Comment by wdm0006** [comment]
The format of these blobs is:

```
entities.user_mentions = [{"name": str, "screen_name": str, "id": int, "id_str": str, "indices": [int, int]}, ... , {}]
entities.urls = [{"display_url": str, "expanded_url": str, "indices": [int, int], "url": str}, ... , {}]
entities.hashtags = [{"text": str, "indices": [int, int]}, ... , {}]
```

You can send yourself a DM on twitter with hashtags and urls and things like that to see what I mean.

**Comment by FreddieV4** [comment]
Just an update; will try to finish this by this weekend

**Comment by freddiev4** [comment]
Working on this branch https://github.com/FreddieV4/twitter-pandas/commit/116568473de71eb262ea4da96dbd5ad0fea489c2. Got the harder method out of the way (minus solving the problem of Unicode Encoding, due to emojis; which is on my TODO).
