### ISSUE TITLE
Implement saved search methods from tweepy

### ISSUE THREAD

**Issue by wdm0006** [wdm0006/twitter-pandas#7]
Implement twitterpandas methods for each of the dataset returning methods in tweepy's saved search methods grouping.

Examples of how to go about this can be found in the existing client.py, where the user methods group has been implemented. Use cursors wherever possible.

**Comment by freddiev4** [comment]
Going to give this one a shot

**Comment by wdm0006** [comment]
Awesome!  So this would include 2 new methods:
- saved_searches
- get_saved_search

If you need help or clarification on anything let me know.

**Comment by freddiev4** [comment]
I'm trying to understand `Return type: list of SavedSearch objects` for the `saved_searches` method.

After running `dir()` on the `SavedSearch` object I receive, I get back:

`['__annotations__', '__call__', '__class__', '__closure__', '__code__', '__defaults__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__get__', '__getattribute__', '__globals__', '__gt__', '__hash__', '__init__', '__kwdefaults__', '__le__', '__lt__', '__module__', '__name__', '__ne__', '__new__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']`

**Comment by wdm0006** [comment]
For most of these objects I've found it simplest to call ._json on the objects to get back the raw dictionary that was used to create them.  Then you can just flatten the dictionary and use the resulting list of flat dictionaries to construct the dataframe. The followers() method in twitterpandas has a good example of this.

**Comment by freddiev4** [comment]
Looking at the tweepy documentation, `API.saved_searches()` takes no params, so if I call `self.client.saved_searches` the data I receive doesn't have a `._json` attribute

**Comment by wdm0006** [comment]
I'll have to look into this more tonight, but it looks like the saved search objects have the data set as class variables here: [tweepy source](https://github.com/tweepy/tweepy/blob/master/tweepy/models.py#L257)

The only one I can see there is the 'created_at' field.  For this, it may be enough for us to just return the saved search ID and created at, to let the user then use the other method (get_saved_search) for more detail.  

Medium term, it'd be nicer to optionally have twitter-pandas return one dataframe with all of the data from get_saved_search for each id from saved_searches.

**Comment by freddiev4** [comment]
```
    # #################################################################
    # #####  Saved Searches Methods                               #####
    # #################################################################
    def saved_searches(self):
        """
        Returns the ID and created_at attributes for the user tied to the API keys.

        :param id_: Specifies the ID or screen name of the user
        :param limit: the maximum number of rows to return (optional, default None for all rows)
        :return:
        """

        data = self.client.saved_searches()

        print(data)

        print(dir(data))
```

`dir(data)` returns 

```
['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_max_id', '_since_id', 'append', 'clear', 'copy', 'count', 'extend', 'ids', 'index', 'insert', 'max_id', 'pop', 'remove', 'reverse', 'since_id', 'sort']
```

**Comment by wdm0006** [comment]
Try looking in data.**dict**

**Comment by freddiev4** [comment]
So the objects are definitely getting returned as class variables. 

Example:

```
SavedSearch(name='hello', id=735570679731507200, created_at=datetime.datetime(2016, 5, 25, 20, 38, 10), query='hello', _api=<tweepy.api.API object at 0x110e2b710>, id_str='735570679731507200', position=None)
SavedSearch(name='api', id=735571588834336768, created_at=datetime.datetime(2016, 5, 25, 20, 41, 47), query='api', _api=<tweepy.api.API object at 0x110e2b710>, id_str='735571588834336768', position=None)
SavedSearch(name='pandas', id=735571678055567365, created_at=datetime.datetime(2016, 5, 25, 20, 42, 8), query='pandas', _api=<tweepy.api.API object at 0x110e2b710>, id_str='735571678055567365', position=None)
```

`get_saved_search(id)` only gets one specific search by id, otherwise `saved_searches()` retrieves all saved searches made by the user. So...unless you want one specific saved search, `saved_searches()` does pretty much everything.

`dict(data)` or `data.__dict__` don't do anything as the objects cannot be converted to dictionaries via these methods.

However, `data.__dict__` does return a dictionary of size two `{'_max_id': None, '_since_id': None}`

**Comment by wdm0006** [comment]
Hey Freddie, got a chance to try it out.  The saved search object has a few class variables that you can access directly.  It's easiest to see in a debugger, but you can get it printed out if you run:

```
tp = TwitterPandas(
        TWITTER_OAUTH_TOKEN,
        TWITTER_OAUTH_SECRET,
        TWITTER_CONSUMER_KEY,
        TWITTER_CONSUMER_SECRET
)

tp.client.create_saved_search(query='list:NASA/astronauts-in-space-now')
temp = tp.client.saved_searches()[0]
print(temp.created_at)
print(temp.id)
print(temp.name)
print(temp.query)
```

calling `__dict__` on that same object gives me:

```
print(temp.__dict__)
>>> {'_api': <tweepy.api.API object at 0x10603feb8>, 'created_at': datetime.datetime(2016, 5, 25, 23, 13, 52), 'id': 735609863095615494, 'query': 'list:NASA/astronauts-in-space-now', 'id_str': '735609863095615494', 'position': None, 'name': 'list:NASA/astronauts-in-space-now'}
```

Hope that helps.

**Comment by freddiev4** [comment]
OK. I get exactly what I was doing wrong after looking at your example.

**Comment by freddiev4** [comment]
PR #10 should solve this issue
